"""Turn harness result packets into src/sc2-runs.js. Read-only on the runs tree."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(r"C:\Users\natha\code\jev-plays-starcraft-2\runs")
OUT = Path(__file__).resolve().parents[1] / "src" / "sc2-runs.js"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def hq_text(value) -> str | None:
    if not isinstance(value, dict) or not value:
        return None
    return ", ".join(f"{name} {health:g}" for name, health in value.items())


# Run evidence served from R2 via /api/media (functions/api/media/[key].js).
# R2 key convention: sc2-<runid>-<filename>. Upload with:
#   npx wrangler r2 object put jevbench-media/sc2-<runid>-screen-capture.mp4 --file <dir>/screen-capture.mp4
MEDIA_BASE = "/api/media"
# Only eye-verified game-only stills are published (desktop captures stay local).
STILL_FILES = (
    "still-gameplay.png",
)


def r2_key(run_id: str, filename: str) -> str:
    stem, ext = filename.rsplit(".", 1)
    return f"sc2-{run_id}-{stem}.{ext}"


def guide_label(control: dict, verification: dict, run_dir: Path) -> str | None:
    if not control.get("guide_expected", True):
        return "none"
    backend = (control.get("guide_backend") or "").strip().lower()
    if not backend and (run_dir / "controller.jsonl").exists():
        # Runs recorded before guide_backend entered control.json: infer from log.
        try:
            with open(run_dir / "controller.jsonl", encoding="utf-8") as fh:
                for _ in range(400):
                    line = fh.readline()
                    if not line:
                        break
                    if '"backend": "ollama"' in line:
                        backend = "ollama"
                        break
        except OSError:
            pass
    if backend == "ollama":
        model = control.get("guide_ollama_model") or "gemma4:e2b"
        return f"{model} via ollama (local)"
    return control.get("guide_model") or verification.get("guide")


def media_for(run_dir: Path, run_id: str) -> dict:
    """Local evidence manifest. URLs resolve once the files are in R2."""
    video = run_dir / "screen-capture.mp4"
    stills = [name for name in STILL_FILES if (run_dir / name).exists()]
    return {
        "hasVideo": video.exists(),
        "video": f"{MEDIA_BASE}/{r2_key(run_id, video.name)}" if video.exists() else None,
        "stills": [
            {"file": name, "url": f"{MEDIA_BASE}/{r2_key(run_id, name)}"}
            for name in stills
        ],
    }


def main() -> None:
    runs = []
    for result_path in ROOT.glob("*/result.json"):
        data = load(result_path)
        control_path = result_path.with_name("control.json")
        control = load(control_path) if control_path.exists() else {}
        verification = data.get("verification") or {}
        via = control.get("jev_via") or verification.get("jev_via") or "untagged"
        runs.append(
            {
                "id": result_path.parent.name,
                "map": data.get("map_name") or "Unknown map",
                "status": data.get("status") or "incomplete",
                "stateMode": control.get("state_mode") or "full",
                "via": via,
                "model": control.get("jev_model") or verification.get("jev_model"),
                "calls": data.get("calls"),
                "cost": data.get("cost"),
                "source": verification.get("source"),
                "heroAlive": verification.get("hero_alive"),
                "hq": hq_text(verification.get("hq_health")),
                "hqMin": verification.get("hq_min_health_observed"),
                "peakScore": verification.get("peak_score"),
                "loop": verification.get("last_loop") or verification.get("loop"),
                "objective": control.get("objective"),
                "guide": guide_label(control, verification, result_path.parent),
                "reason": data.get("reason"),
                "media": media_for(result_path.parent, result_path.parent.name),
            }
        )
    runs.sort(key=lambda row: row["id"], reverse=True)
    payload = json.dumps(runs, indent=2)
    OUT.write_text(
        "/** Scored StarCraft II harness packets. Generated by scripts/build_sc2_runs.py. */\n"
        f"export const SC2_RUNS = {payload};\n\n"
        "export const BENCH = {\n"
        '  updatedLabel: "21 Sep 2026",\n'
        f"  scoredRuns: {len(runs)},\n"
        f"  verifiedWins: {sum(1 for row in runs if row['status'] == 'victory')},\n"
        "  games: 1,\n"
        '  gameNote: "StarCraft II",\n'
        "  modelsListed: 8,\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} runs={len(runs)}")


if __name__ == "__main__":
    main()
