"""Turn Minecraft agent runs (pulled from the .10 box) into src/minecraft-runs.js.

Source: runs/minecraft-incoming/<RUN>/ (metadata) + R2 for media.
Read-only on the incoming tree. Mirrors scripts/build_sc2_runs.py.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(r"C:\Users\natha\code\jev-plays-starcraft-2\runs\minecraft-incoming")
OUT = Path(__file__).resolve().parents[1] / "src" / "minecraft-runs.js"

MEDIA_BASE = "/api/media"


def load(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return {}


def run_number(run_id: str) -> int:
    digits = "".join(ch for ch in run_id if ch.isdigit())
    return int(digits) if digits else 0


def norm_status(summary: dict) -> str:
    status = (summary.get("status") or "").strip()
    outcome = (summary.get("outcome") or "").strip()
    if summary.get("won") is True or status == "victory":
        return "victory"
    if status:
        return status
    if outcome:
        return outcome
    return "incomplete"


def note_text(summary: dict) -> str | None:
    for key in ("note", "root_cause", "rootCause"):
        val = summary.get(key)
        if isinstance(val, str) and val.strip():
            return val.strip()
        if isinstance(val, list) and val:
            return "; ".join(str(x) for x in val)[:400]
    return None


def media_for(run_dir: Path, run_id: str) -> dict:
    video = run_dir / "full-playthrough.mp4"
    stills = sorted(p.name for p in run_dir.glob("still-*.png"))
    return {
        "hasVideo": video.exists(),
        "video": f"{MEDIA_BASE}/mc-{run_id}-full-playthrough.mp4" if video.exists() else None,
        "stills": [
            {"file": name, "url": f"{MEDIA_BASE}/mc-{run_id}-{name}"} for name in stills
        ],
    }


def main() -> None:
    runs = []
    for run_dir in sorted(ROOT.glob("NEW_RUN*"), key=lambda p: run_number(p.name)):
        summary = load(run_dir / "summary.json")
        config = load(run_dir / "run-config.json")
        if not summary and not config:
            continue
        runs.append(
            {
                "id": run_dir.name,
                "game": "Minecraft Java 1.16.5",
                "status": norm_status(summary),
                "won": bool(summary.get("won")),
                "dragonKilled": bool(summary.get("dragonKilled")),
                "steps": summary.get("steps") or summary.get("decisions"),
                "stage": summary.get("stage") or None,
                "planner": summary.get("plannerModel") or config.get("planner"),
                "controller": config.get("controller") or "typesafe/jev-1.13",
                "difficulty": config.get("difficulty"),
                "seed": config.get("seed"),
                "note": note_text(summary),
                "milestones": summary.get("milestones") or None,
                "media": media_for(run_dir, run_dir.name),
            }
        )
    runs.sort(key=lambda row: run_number(row["id"]), reverse=True)
    payload = json.dumps(runs, indent=2)
    won = sum(1 for row in runs if row["status"] == "victory")
    OUT.write_text(
        "/** Scored Minecraft agent runs (from the .10 box). Generated by scripts/build_minecraft_runs.py. */\n"
        f"export const MC_RUNS = {payload};\n\n"
        "export const MC_BENCH = {\n"
        '  updatedLabel: "23 Sep 2026",\n'
        f"  scoredRuns: {len(runs)},\n"
        f"  verifiedWins: {won},\n"
        "  games: 1,\n"
        '  gameNote: "Minecraft Java 1.16.5 (Ender Dragon)",\n'
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} runs={len(runs)} wins={won}")


if __name__ == "__main__":
    main()
